### ISSUE TITLE
CORS error for IONApi in the sample app

### ISSUE THREAD

**Issue by DXCdhenningsver** [infor-cloud/m3-h5-sdk#42] opened 2020-04-29 11:14 UTC
## Description
I have compiled the sample app and installed it in our MT environmen. The M3 api calls seems to work ok but for the IONApi parts (IDM and IONApiSocial) I get a CORS error:
![image](https://user-images.githubusercontent.com/39490833/80589703-f6a4ce00-8a1a-11ea-8397-4f77d5aaccd0.png)

I just downloaded the sample zip and unpacked it. Run npm install then odin build. Then I installed the zip through H5 Administration

## Versions
as per infor-m3-odin-sample-soho-2.2.1

**Comment by anhallbe** [comment] 2020-04-29 14:32
That's strange.. It looks like a configuration issue to me, where the ION API proxy is not setting the `Access-Control-Allow-Origin` header correctly. @karinpb do you have any idea what's going on here?

**Comment by alliancehaydenm** [comment] 2020-05-04 23:22
Hi Andreas & team,

I'm still having this same CORS issue on the other thread raised here on github. Subscribing here for any updates :)

Hayden.

**Comment by karinpb** [comment] 2020-06-17 14:26
It seems like the URL is missing the tenantid, it should contain the tenantid before IDM to call ION API. That makes me think that it is a mismatch between the support that we have for the IDM proxy that we can use On-prem and calling ION API. The URL goes to the ION API but the link looks like it would when calling the H5 internal IDM proxy, so the link is incorrect. Perhaps there is another error earlier that we are not seeing in the screenshot?

@anhallbe please try and run the sample in a cloud environment and check the URL. Could it be that the IDM service is not getting the tenantid correctly or there is a mismatch when it detects the mode?

@DXCdhenningsver Is this still an issue for you?

**Comment by DXCdhenningsver** [comment] 2020-06-18 06:22
@karinpb I tried with the latest version (infor-m3-odin-sample-soho-3.0.0-next.4) but I get the same error.
I was just testing the process of compiling and installing an app so I don't have an actual case with an own app with the issue.

**Comment by karinpb** [comment] 2020-06-18 07:48
Thank you for the update @DXCdhenningsver . We'll see if @anhallbe  can re-create the issue using just the samples and a tenant in that region.

**Comment by anhallbe** [comment] 2020-06-22 12:57
@DXCdhenningsver could you try with the latest pre-release (`next.5`, which was published today)?

1. Install the latest CLI: `npm i -g @infor-up/m3-odin-cli@next`
2. Download, install & build sample: https://github.com/infor-cloud/m3-h5-sdk/tree/master/m3-odin/samples

**Comment by DXCdhenningsver** [comment] 2020-06-22 14:38
Unfortunately it is still the same issue:
![image](https://user-images.githubusercontent.com/39490833/85300233-94120080-b4a6-11ea-8e3e-93ddca88b2dd.png)

As karinpb mentioned it seems like the tenant id is missing from the ionapi link to the api, it is calling https://mingle-ionapi.eu1.inforcloudsuite.com/IDM/api/items/search?$includeCount=true&$limit=20&$offset=0&$query=%2FMDS_File but it should be https://mingle-ionapi.eu1.inforcloudsuite.com/_**TENANT_ID**_/IDM/api/items/search?$includeCount=true&$limit=20&$offset=0&$query=%2FMDS_File

**Comment by anhallbe** [comment] 2020-06-23 09:03
@DXCdhenningsver are you seeing any values for "Tenant" and "ionApiUrl" in the User Context sample?

![image](https://user-images.githubusercontent.com/4991954/85384164-2830a600-b541-11ea-9250-8db5a080894d.png)

**Comment by DXCdhenningsver** [comment] 2020-06-23 09:16
@anhallbe Yes, all these properties has values
![image](https://user-images.githubusercontent.com/39490833/85385812-059f8c80-b543-11ea-8554-f07332da36fd.png)

**Comment by anhallbe** [comment] 2020-12-22 09:19
@DXCdhenningsver I'm closing this as there hasn't been any activity in 6 months, and we can't seem to reproduce the issue.

Please create a new ticket with reproduction steps if you are still experiencing issues.

**Closed by anhallbe** 2020-12-22 09:19 UTC
Labels: question
