### ISSUE TITLE
Fails to get user context, Transaction GetUserData in program MNS150MI requires a value for field USID

### ISSUE THREAD

**Issue by bjohog** [infor-cloud/m3-h5-sdk#23] opened 2020-02-13 14:57 UTC
The user context can not be loaded after I have tried to sign in.
I'll have the same issue for an app created for the customer and we need to have that fixed as soon as possible.

**To Reproduce**
I'll start the SoHo Xi sample. Then I press the Customer app in the list to the left.
The sign-in window is shown and I enter my credentials.
Then I get the following errror message:

![image](https://user-images.githubusercontent.com/39406230/74446835-c799aa00-4e78-11ea-85c1-c992b8ad2bb9.png)

![image](https://user-images.githubusercontent.com/39406230/74446911-d7b18980-4e78-11ea-9f06-1cce74afee72.png)

**Expected behavior**
Able to sign in and to use user context to be able to utilize settings from MNS150

**Comment by kakaluto** [comment] 2020-02-17 14:55
hi. I've got the same problem when using the framework for multi tenant.
It seems that the userConext is retrieved by miService and not IonApiService :

 UserServiceCore.prototype.loadUserData = function () {
      var _this = this;
      var parameters = {};
      var usid = this.m3User;
      var request = {
         program: 'MNS150MI',
         transaction: 'GetUserData'
      }; 
      this.miService.execute(request).subscribe(function (response) {
         _this.onUserData(response.item);
      }, function (response) {
         _this.rejectQueue(response.errorMessage);
      });

I think that we need an upgrade of the framework for local developpement for cloud client

**Comment by anhallbe** [comment] 2020-02-18 17:02
@bjohog and @kakaluto 
Are you using the Multi-Tenant Login Utility?
https://github.com/infor-cloud/m3-h5-sdk/tree/master/login

**Comment by kakaluto** [comment] 2020-02-18 17:23
Hi Andreas,
yes, i use it to retrieve the tocken. I've got the cookies and the token to use in the ionApiService.setDevelopmentToken()
This works for all apis. But when i start in dev mode https://localhost:443, the ionApiService retrieves me the Item List (MMS200MI/LstItmByItm), but before that, i have an exception 

UserContext {numberFormatOptions: {…}, errorMessage: "Failed to call MNS150MI.GetUserData 500"}
numberFormatOptions: {separator: "."}
errorMessage: "Failed to call MNS150MI.GetUserData 500"
__proto__: ErrorState

because the framework uses the miService instead of ionApiService (i think)...

**Comment by bjohog** [comment] 2020-02-19 10:18
@anhallbe 
I'm not using the Multi-Tenant Login Utility.

**Comment by anhallbe** [comment] 2020-02-20 11:59
So there seems to be two different issues here, and I can't reproduce any of them. @bjohog , yes you need the Multi-Tenant Login Utility to develop against a multi-tenant environment. I just tested the following, without any issues:

1. Downloaded & extracted infor-m3-odin-sample-soho-2.1.2.zip
2. Run `npm install` in the extracted project.
3. Download & extract OdinSDKMTLoginUtility.zip
4. In the extracted OdinSDKMTLoginUtility folder, I launch "Launch M3 only Login.cmd" and configure:
   4.1. Go to Settings
   4.2 Select project folder (the extracted project in step 1)
   4.3 Enter a Tenant URL: "https://portal-hostname/TENANT_ID"
   4.4 Enter the M3 URL: "https://m3-hostname/mne"
  4.5 Click "Verify"
  4.6 Go to "Login", and log in.
5. In the extracted project folder, I run `odin set ion-proxy https://ionapi-hostname/TENANT_ID` 
6. Run `odin serve --multi-tenant`
7. In a browser, I verify that the communication works by:
   7.1 Launch all the M3 samples, and verify that customer/context data is fetched and displayed
   7.2 Launch the ION API Social sample and verify that the user can be fetched through ION API.

No errors are logged.

**Comment by bjohog** [comment] 2020-02-20 12:43
@anhallbe 
my customer is not on a Multi-Tenant installation they are running M3 13.3 local installation. 
Can we set up a meeting where I can show the problem to you?

**Comment by karinpb** [comment] 2020-02-24 12:04
@bjohog M3 13.3 needs to be updated with MCP4 in order to get a fix for MNS150 so that USID is no longer a mandatory parameter and the current user will be used instead of passing in the parameter.
There issue that @kakaluto commented about is not the same issue. We'll look into that one, but basically I'm afraid that needs to be reported in a separate ticket, since it's not related to "Transaction GetUserData in program MNS150MI requires a value for field USID".

**Comment by anhallbe** [comment] 2020-02-24 12:31
@kakaluto please follow the steps in https://github.com/infor-cloud/m3-h5-sdk/issues/23#issuecomment-588985277 and see if you can get it to work.

The `UserService` does not use ION API, which is why the MT Login tool is needed (and the `--multi-tenant` flag). If you still experience problems, please create a new issue with more context.

Closing this issue, as @karinpb has provided the solution https://github.com/infor-cloud/m3-h5-sdk/issues/23#issuecomment-590289019

**Closed by anhallbe** 2020-02-24 12:31 UTC
Labels: bug

**Comment by bjohog** [comment] 2020-02-27 07:46
> @bjohog M3 13.3 needs to be updated with MCP4 in order to get a fix for MNS150 so that USID is no longer a mandatory parameter and the current user will be used instead of passing in the parameter.
> The issue that @kakaluto commented about is not the same issue. We'll look into that one, but basically, I'm afraid that needs to be reported in a separate ticket since it's not related to "Transaction GetUserData in program MNS150MI requires a value for field USID".

I works perfectly fine now, I found the correction JT-903123. Thanks for the help.
