### ISSUE TITLE
Problem calling ION Apis from m3-h5

### ISSUE THREAD

**Issue by NikitasX** [infor-cloud/m3-h5-sdk#84] opened 2021-02-03 10:18 UTC
Hello, 

For the past week I've been trying to call an ION Api endpoint from inside m3-h5 (using an odin application) with no success!

I tried setting a developmentToken and calling the same endpoint and it worked correctly. However, when I uploaded my odin application to the m3-h5 server I always got an error 404 when calling the '/grid/rest/security/sessions/oauth?rid=xxx' url.

From what I can tell the problem arises when the ionService.execute is trying to find and retrieve the token on the url above (which seems to not work).

Below u will find the code I am using to make the call to the ION Api endpoint:
`    
    this.userContext.ionApiUrl = 'https://someUrl.com';
    this.userService.updateUserContext(this.userContext, null);
    let formService = new FormService(this.userService);

    let ionApiService = new IonApiService(
      this.http,
      formService,
      this.ionApiConfig
    );

    var request = {
      body: {
        validationString:
          'randomString',
      },
      headers: {
        'content-type': 'application/json, text/plain',
        Accept: '*/*',
      },
      ionApiRetry: false,
      method: 'POST',
      responseType: 'json',
      source: 'My Awesome Application',
      url: 'https://someUrl.com/api/Path',
    } as IIonApiRequest;
    
    ionApiService.execute(request).subscribe(
      (data) => {
        console.log(data);
      },
      (error) => {
        console.log(error);
      }
    );
    `

Any help would be appreciated as I am currently stuck and can't seem to find a solution to this! The m3-h5 version I am running on my server is version 15.1.4.

Thanks in advance!

**Comment by anhallbe** [comment] 2021-02-03 18:42
Hi @NikitasX!
Is this an Angular app? If that's the case, you're not supposed to create instances of the services yourself. They will be injected into your components/services using DI. Example:

```typescript
...
import { IonApiService } from "@infor-up/m3-odin-angular";

@Component(...)
export class MyComponent {
  constructor(private ionApiService: IonApiService) {}  // The framework creates the instance, and injects it here
  
  makeTheRequest() {
    this.ionApiService.execute(....).subscribe();
  }
}
```

**Comment by NikitasX** [comment] 2021-02-04 07:15
I tried injecting the IonApiService but the problem still persists. Even trying to open the url via the browser just throws a 404 error.

**Comment by anhallbe** [comment] 2021-02-04 09:27
Have you tried running the sample project in your environment?

I'm trying to figure out whether the issue is in your server config or your client code. Please install the latest version of the CLI (4.0.0) and [download/build/upload a sample project](https://github.com/infor-cloud/m3-h5-sdk#-samples), and see if the problem occurs with that.

**Comment by NikitasX** [comment] 2021-02-05 13:17
I uploaded the sample project to my h3-m5 and tried using the "ION Api social" -> Load button (which I saw was using the same execute function/structure as my project) and the error still persists (404 not found /grid/rest/security/sessions/oauth?)

**Comment by karinpb** [comment] 2021-02-05 14:07
@NikitasX Just to make sure, you are not running M3 on prem? Calling ION APIs is only supported in the M3 CE.

**Comment by NikitasX** [comment] 2021-02-08 09:20
Yeah M3 is running on premises not on the cloud. Is there any other way/workaround to call the ION Api like you would in the cloud? What I am trying to do is basically get the authentication the user provided when logging into M3 and pass it over to ION Api and thus call it without having to re-authenticate.

**Comment by anhallbe** [comment] 2021-02-17 12:39
I think this is outside the scope of the SDK.
The only way I could think of achieving this is registering your app in ION API, and retrieving an access token from there (with whatever login mechanism you have). You'd need to manage the accessToken/refreshToken/redirects etc yourself, though.

But I think you're better off asking the M3 Support regarding this.

**Closed by anhallbe** 2021-02-17 12:39 UTC
